{% set name = "oauthlib" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23a8208d75b902797ea29fd31fa80a15ed9dc2c6c16fe73f5d346f83f6fa27a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - cryptography
    - pyjwt >=1.0.0
    - blinker

test:
  imports:
    - oauthlib
    - oauthlib.oauth1
    - oauthlib.oauth1.rfc5849
    - oauthlib.oauth1.rfc5849.endpoints
    - oauthlib.oauth2
    - oauthlib.oauth2.rfc6749
    - oauthlib.oauth2.rfc6749.clients
    - oauthlib.oauth2.rfc6749.endpoints
    - oauthlib.oauth2.rfc6749.grant_types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/idan/oauthlib
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
  dev_url: https://github.com/idan/oauthlib
  doc_url: https://oauthlib.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
